project:
  type: website
  output-dir: docs

website:
  title: "Ahmed Mohamoud"
  navbar:
    left:
      - href: index.qmd
        text: About
      - packages.qmd
      - tutorials.qmd
      - publications.qmd

format:
  html:
    include-in-header: _analytics.html
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
