project:
  type: website
  output-dir: docs

website:
  title: "Ahmed Mohamoud"
  navbar:
    left:
      - href: index.qmd
        text: About
      - packages.qmd
      - tutorials.qmd
      - publications.qmd
  page-footer: 
    left: "@ Ahmed Mohamoud 2025"
    right: "Built with Quarto"
  
format:
  html:
    include-in-header: _analytics.html
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: false
    page-layout: article
