project:
  type: website
  output-dir: docs

website:
  title: "Ahmed Mohamoud"
  navbar:
    left:
      - href: index.qmd
        text: About
      - publications.qmd
    google-analytics:
    tracking-id: G-34D8XG2PNV
    anonymize-ip: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
